---
- name: Install {{custom_domain}}
  import_role:
    name: lokal.core.lokal
    tasks_from: install
  vars:
    app_name: "{{custom_name}}"  # required for git checkout and
    app_git: "{{custom_git}}"
    app_domain: "{{custom_domain}}"
    app_version: "{{custom_ref}}"
    app_port: "{{custom_port}}"
    app_dirs: "{{custom_dirs | list}}"
