---
- name: Install users
  include_role:
    name: lokal.core.lokal
    tasks_from: install
  vars:
    app: users
    data_dirs:
    - auth/conf
    - auth/data
    - ldap
    app_templates:
      authelia.yml: auth/conf/configuration.yml
      lldap.toml: ldap/lldap_config.toml
