---
- name: Get docker gid
  ansible.builtin.shell:
    cmd: 'cat /etc/group | grep docker | cut -d: -f 3'
  register: docker_gid_output

- name: Register runtime and internal variables
  set_fact:
    uid: '{{ansible_facts["user_uid"]}}'
    gid: '{{ansible_facts["user_gid"]}}'
    tz: '{{ansible_facts["date_time"]["tz"]}}'
    gid_docker: '{{docker_gid_output.stdout}}'
    external_ipv4: '{{ansible_facts["default_ipv4"]["address"]}}'
    today: '{{ansible_facts["date_time"]["date"]}}'
    project_root: "{{lokal_root}}/{{primary_domain}}"
    lokal_logroot: "{{lokal_root}}/{{primary_domain}}/logs"
    project_name: "{{primary_domain.replace('.', '').replace('-', '')}}"

- name: "Bootstrap basic infrastructure"
  include_tasks:
    file: bootstrap.yml
  when: not backup is defined and not restore is defined and not remove is defined and (not install is defined or install == "all" or "lokal" in install)