---
- name: Remove {{app_db_name}} PostgreSQL database
  ansible.builtin.shell:
    cmd: >
      {{dc}} exec postgres
      psql -c 'DROP DATABASE "{{app_db_name}}"' postgres postgres;
    chdir: "{{project_root}}"
  ignore_errors: true

- name: Remove {{app_db_user}} PostgreSQL user
  ansible.builtin.shell:
    cmd: >
      {{dc}} exec postgres
      psql -c 'DROP USER "{{app_db_user}}"' postgres postgres;
    chdir: "{{project_root}}"
  ignore_errors: true
