---
- name: Install your-app
  include_role:
    name: lokal.core.lokal
    tasks_from: install
  vars:
    app_dirs:
    - data
    - config
    app_templates:
      service.conf: config/service.conf
    app_files:
      your-static-file.txt: data/initial-data.txt
    app_db: "mysql"
    app_start: false # you can postpone starting (by defaults the container starts)

# ...
# You can do more steps before lunching your docker-compose
# ...

# This is the command to start your app manually
- name: Start the app
  ansible.builtin.shell:
    cmd: "{{dc}} up -d"
    chdir: "{{app_root}}"